-- luacheck: globals describe it before_each after_each setup teardown assert spy stub mock pending FenUI CreateFrame UIParent NineSliceLayouts NineSliceUtil
describe("FenUI BlizzardBridge", function()
    setup(function()
        require("Core.FenUI")
        require("Utils.Utils")
        require("Core.Tokens")
        require("Core.ThemeManager")
        require("Core.BlizzardBridge")
        require("Utils.UI")
    end)

    describe("Layout Validation", function()
        it("should check if layout exists", function()
            assert.is_true(FenUI:LayoutExists("Simple"))
            assert.is_true(FenUI:LayoutExists("SimplePanelTemplate"))
            assert.is_false(FenUI:LayoutExists("NonExistent"))
        end)

        it("should resolve layout names", function()
            assert.is_equal(FenUI:ResolveLayoutName("Simple"), "SimplePanelTemplate")
            assert.is_equal(FenUI:ResolveLayoutName("SimplePanelTemplate"), "SimplePanelTemplate")
        end)

        it("should get available layouts", function()
            local layouts = FenUI:GetAvailableLayouts(false)
            assert.is_true(#layouts > 0)
            local foundSimple = false
            for _, name in ipairs(layouts) do
                if name == "Simple" then foundSimple = true end
            end
            assert.is_true(foundSimple)

            local allLayouts = FenUI:GetAvailableLayouts(true)
            assert.is_true(#allLayouts >= #layouts)
        end)
    end)

    describe("Custom Border Engine", function()
        it("should apply and hide custom borders", function()
            local frame = CreateFrame("Frame")
            local success = FenUI:ApplyBorder(frame, "ModernDark")
            assert.is_true(success)
            assert.is_true(frame.borderApplied)
            assert.is_not_nil(frame.customBorder.TopLeftCorner)
            assert.is_true(frame.customBorder.TopLeftCorner:IsShown())

            FenUI:HideCustomBorder(frame)
            assert.is_false(frame.borderApplied)
            assert.is_false(frame.customBorder.TopLeftCorner:IsShown())
        end)

        it("should handle missing border packs", function()
            local frame = CreateFrame("Frame")
            local success = FenUI:ApplyBorder(frame, "NonExistentPack")
            assert.is_false(success)
        end)
    end)

    describe("NineSlice Application", function()
        it("should apply layouts and handle margins", function()
            local frame = CreateFrame("Frame")
            local success = FenUI:ApplyLayout(frame, "Simple", "test-kit", { top = 10, left = 10, bottom = 10, right = 10 })
            assert.is_true(success)
            assert.is_equal(frame.fenUILayout, "SimplePanelTemplate")
            assert.is_equal(frame.fenUITextureKit, "test-kit")
            
            -- Check margins applied to corners
            local _, _, _, x, y = frame.TopLeftCorner:GetPoint()
            assert.is_equal(x, 10)
            assert.is_equal(y, -10)
        end)

        it("should apply layout direct", function()
            local frame = CreateFrame("Frame")
            local success = FenUI:ApplyLayoutDirect(frame, "SimplePanelTemplate")
            assert.is_true(success)
        end)
    end)

    describe("Layout Utilities", function()
        it("should get layout pieces", function()
            local frame = CreateFrame("Frame")
            FenUI:ApplyLayout(frame, "Simple")
            local pieces = FenUI:GetLayoutPieces(frame)
            assert.is_not_nil(pieces)
            assert.is_not_nil(pieces.TopLeftCorner)
        end)

        it("should set layout colors", function()
            local frame = CreateFrame("Frame")
            FenUI:ApplyLayout(frame, "Simple")
            FenUI:SetLayoutColor(frame, 1, 0, 0, 1)
            -- Check vertex color on one piece
            local r, g, b, a = frame.TopLeftCorner:GetVertexColor()
            assert.is_equal(r, 1)
        end)

        it("should set center color", function()
            local frame = CreateFrame("Frame")
            FenUI:ApplyLayout(frame, "Simple")
            FenUI:SetLayoutCenterColor(frame, 0, 1, 0)
            local r, g, b = frame.Center:GetVertexColor()
            assert.is_equal(g, 1)
        end)

        it("should set border color", function()
            local frame = CreateFrame("Frame")
            FenUI:ApplyLayout(frame, "Simple")
            FenUI:SetLayoutBorderColor(frame, 0, 0, 1)
            local r, g, b = frame.TopLeftCorner:GetVertexColor()
            assert.is_equal(b, 1)
        end)

        it("should hide and show layout", function()
            local frame = CreateFrame("Frame")
            FenUI:ApplyLayout(frame, "Simple")
            FenUI:HideLayout(frame)
            assert.is_false(frame.TopLeftCorner:IsShown())
            FenUI:ShowLayout(frame)
            assert.is_true(frame.TopLeftCorner:IsShown())
        end)
    end)

    describe("Frame Creation Helpers", function()
        it("should create frames with layout", function()
            local frame = FenUI:CreateFrameWithLayout("Frame", "TestFrame", UIParent, "Simple")
            assert.is_not_nil(frame)
            assert.is_equal(frame.fenUILayout, "SimplePanelTemplate")
        end)

        it("should create inset frame", function()
            local frame = FenUI:CreateInsetFrame("TestInset", UIParent)
            assert.is_not_nil(frame)
            assert.is_equal(frame.fenUILayout, "InsetFrameTemplate")
        end)
    end)

    describe("TextureKit Utilities", function()
        it("should check known texture kits", function()
            assert.is_true(FenUI:IsKnownTextureKit("warwithin"))
            assert.is_false(FenUI:IsKnownTextureKit("unknown"))
        end)

        it("should get known texture kits", function()
            local kits = FenUI:GetKnownTextureKits()
            assert.is_true(#kits > 0)
        end)
    end)
end)

